run:
  timeout: 5m
  tests: true
linters:
  enable:
    - govet
    - gofmt
    - goimports
    - revive
    - staticcheck
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gofmt
        - goimports
      text: "file is not gofmt-ed"
