name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOTOOLCHAIN: auto
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install tools
        run: |
          make lint >/dev/null 2>&1 || true
          make tools

      - name: Run lint
        run: make lint

      - name: Run unit tests
        run: make test

      - name: Run end-to-end tests
        run: make e2e

      - name: Build Docker image
        run: docker build -t pellets-tracker:${{ github.sha }} .
